import type { Metadata } from "next";
import React from "react";
import styled from "styled-components";

export const metadata: Metadata = {
  title: "mp-4 | CS391",
  description: "Generated by create next app",
};

const StyledBody = styled.body `
    font-family: Garamond, serif;
`

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <StyledBody>{children}</StyledBody>
    </html>
  );
}
